version: '2'
services:
    bee-app:
        image: bee
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bee-mysql:3306/bee?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bee-mysql:
        extends:
            file: mysql.yml
            service: bee-mysql
